### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by i55code** [Unbabel/MT-Telescope#2]
## 🐛 Bug

Hi, I have two questions here as I attempt to run the interface: 
1. pip install mt-telescope: This removes the most updated version of COMET (unbabel-comet==1.0.0rc9) and replaces it with unbabel-comet==1.0.0rc2, is this supposed to do that? Or can MT-telescope be updated with the most recent version of COMET? 
2. telescope streamlit produced the following error in mutiple machines that I tried: 

Traceback (most recent call last):
  File "/home/.local/lib/python3.8/site-packages/MeCab/__init__.py", line 133, in __init__
    super(Tagger, self).__init__(args)
RuntimeError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/.local/bin/telescope", line 5, in <module>
    from telescope.cli import telescope
  File "/home/.local/lib/python3.8/site-packages/telescope/cli.py", line 26, in <module>
    from telescope.metrics import AVAILABLE_METRICS, PairwiseResult
  File "/home/.local/lib/python3.8/site-packages/telescope/metrics/__init__.py", line 1, in <module>
    from .sacrebleu import sacreBLEU
  File "/home/.local/lib/python3.8/site-packages/telescope/metrics/sacrebleu/__init__.py", line 1, in <module>
    from .metric import sacreBLEU
  File "/home/.local/lib/python3.8/site-packages/telescope/metrics/sacrebleu/metric.py", line 20, in <module>
    import sacrebleu
  File "/home/.local/lib/python3.8/site-packages/sacrebleu.py", line 962, in <module>
    'ja-mecab': TokenizeMeCab().tokenize,
  File "/home/.local/lib/python3.8/site-packages/sacrebleu.py", line 929, in __init__
    self.tagger = MeCab.Tagger("-Owakati")
  File "/home/.local/lib/python3.8/site-packages/MeCab/__init__.py", line 135, in __init__
    raise RuntimeError(error_info(rawargs)) from ee
RuntimeError: 
----------------------------------------------------------

Failed initializing MeCab. Please see the README for possible solutions:

    https://github.com/SamuraiT/mecab-python3#common-issues

If you are still having trouble, please file an issue here, and include the
ERROR DETAILS below:

    https://github.com/SamuraiT/mecab-python3/issues

issueを英語で書く必要はありません。

------------------- ERROR DETAILS ------------------------
arguments: -Owakati
[ifs] no such file or directory: /usr/local/etc/mecabrc
----------------------------------------------------------

**Comment by i55code** [comment]
I used another machine for installation, and MT telescope works without producing this error. Though I can use the new machine for running MT telescope, I still do want to know how to resolve the above error. Feel free to let me know. Thanks.

**Comment by federicocesena** [comment]
For me the error is:
Error: Invalid value: File does not exist: /app.py

I did not install from the source, but from pip.
